In [2]:
# Importation des packages requis
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd
from requests import get

# Initialisation d'un DataFrame vide
df = pd.DataFrame()

# Parcoure des 111 premières pages

# for p in range(1, 112) #la ligne normale
for p in range(1, 3): 
    url = f'https://dakar-auto.com/senegal/motos-and-scooters-3?page={p}'
    res = requests.get(url)
    soup = bs(res.text, 'html.parser')
    containers = soup.find_all('div', class_='listing-card')

    data = []
    
    for container in containers:
        name = container.find('h2', class_='listing-card__header__title mb-md-2 mb-0').text.strip() 
        price = container.find('h3', class_='listing-card__header__price font-weight-bold text-uppercase mb-0').text.strip().replace('\u202f','').replace(' F CFA','')
        Ref = container.find('li', class_='listing-card__attribute list-inline-item').text.strip().replace('\u202f','').replace('Ref.','')
        proprio = container.find('p', class_='time-author m-0').text.strip().replace('\u202f','').replace('Par ','')
        adr_vente_commune = container.find('span', class_='town-suburb d-inline-block').text.strip().replace('\u202f','').replace(',','')
        adr_vente_region = container.find('span', class_='province font-weight-bold d-inline-block').text.strip()  
        kilometrage = container.find('i',class_='v-icon icon-road-perspective')
       
        
        
     
        
        data.append({'Marque_Modele_Annee': name, 
                     'Prix (F CFA)' : price, 
                     'Ref.' : Ref, 
                     'Proprio' : proprio, 
                     'Adr_Commune' : adr_vente_commune,
                     'Adr_Region' : adr_vente_region, 
                     'Kilometrage' : kilometrage, 
                     }) 
    
    # Append data to the DataFrame
    df = pd.DataFrame(data)

#Print the DataFrame
print(df)

           Marque_Modele_Annee Prix (F CFA)     Ref.  \
0             Yamaha TMax 2012      2350000   138801
1         Piaggio Liberty 2020       320000   138717
2           Peugeot Tweet 2022       350000   138623
3              Kymco Mxer 2020       400000   138598
4            Kymco People 2017       450000   138592
5         Piaggio Beverly 2011       400000   138510
6         Piaggio Carnaby 2009       550000   138498
7           Kymco Xciting 2021      1800000   138452
8                 KTM SMR 2013      1850000   138437
9             KTM jakarta 2023       350000   138362
10          Kymco Agility 2021       380000   138373
11          Kymco Agility 2019          150   138317
12         Triumph Sprint 2000      1600000   138267
13           Suzuki GSX-F 1994      1200000   138268
14                 BMW GS 2015      3500000   138206
15          Peugeot Scoot 2019       750000   138200
16           Yamaha X-Max 2006       700000   138190
17         Suzuki Burgman 2021      1300000   138179
18          Kymco Xciting 2021      1900000   138154
19  Honda XRV Africa Twin 2018      3600000   138100

                      Proprio          Adr_Commune Adr_Region Kilometrage
0       Cheikh Tidiane Ndiaye                  VDN      Dakar          []
1                     doul ba        Hann Maristes      Dakar          []
2            ABDOULAYE SIDIBE           Scat Urbam      Dakar          []
3                   Ahmed Sow               Sipres      Dakar          []
4              Mouhamed Niang         Hann Bel-Air      Dakar          []
5                Fallou Gueye          Ouest Foire      Dakar          []
6              Abdoulaye WELE              Kaolack    Kaolack          []
7                 MAME CHEIKH             Mamelles      Dakar          []
8              Christian Faye             Thiaroye      Dakar          []
9                Cheikh Toure              Point-E      Dakar          []
10             Max2roues Diaw        Hann Maristes      Dakar          []
11             Boubacar Seydi          Keur Massar      Dakar          []
12          Jean philipp Coly    Sicap Sacré Coeur      Dakar          []
13          Jean philipp Coly    Sicap Sacré Coeur      Dakar          []
14              Babacar Dramé          Keur Massar      Dakar          []
15                Abdoul Diop          Biscuiterie      Dakar          []
16              Mathieu Sagna        Sicap Liberté      Dakar          []
17            LodiaMiff Deals           Nord Foire      Dakar          []
18                   Al Amine  Liberté 6 extension      Dakar          []
19  HONDA AFRICA TWIN CRF1000              Plateau      Dakar          []

In [3]:
# Affichange des 5 premieres lignes 
df.head()

,Marque_Modele_Annee,Prix (F CFA),Ref.,Proprio,Adr_Commune,Adr_Region,Kilometrage
0,Yamaha TMax 2012,2350000,138801,Cheikh Tidiane Ndiaye,VDN,Dakar,[]
1,Piaggio Liberty 2020,320000,138717,doul ba,Hann Maristes,Dakar,[]
2,Peugeot Tweet 2022,350000,138623,ABDOULAYE SIDIBE,Scat Urbam,Dakar,[]
3,Kymco Mxer 2020,400000,138598,Ahmed Sow,Sipres,Dakar,[]
4,Kymco People 2017,450000,138592,Mouhamed Niang,Hann Bel-Air,Dakar,[]

In [1]:
# Importation de packages requis
import pandas as pd
import numpy as np

In [6]:
# Reorganisation des colonnes 

df = df[['Marque_Modele_Annee', 'Kilometrage', 'Prix (F CFA)', 'Ref.', 'Adr_Commune', 'Adr_Region', 'Proprio' ]]

In [7]:
# Verification de la reorganisation des colonnes
df

,Marque_Modele_Annee,Kilometrage,Prix (F CFA),Ref.,Adr_Commune,Adr_Region,Proprio
0,Yamaha TMax 2012,[],2350000,138801,VDN,Dakar,Cheikh Tidiane Ndiaye
1,Piaggio Liberty 2020,[],320000,138717,Hann Maristes,Dakar,doul ba
2,Peugeot Tweet 2022,[],350000,138623,Scat Urbam,Dakar,ABDOULAYE SIDIBE
3,Kymco Mxer 2020,[],400000,138598,Sipres,Dakar,Ahmed Sow
4,Kymco People 2017,[],450000,138592,Hann Bel-Air,Dakar,Mouhamed Niang
5,Piaggio Beverly 2011,[],400000,138510,Ouest Foire,Dakar,Fallou Gueye
6,Piaggio Carnaby 2009,[],550000,138498,Kaolack,Kaolack,Abdoulaye WELE
7,Kymco Xciting 2021,[],1800000,138452,Mamelles,Dakar,MAME CHEIKH
8,KTM SMR 2013,[],1850000,138437,Thiaroye,Dakar,Christian Faye
9,KTM jakarta 2023,[],350000,138362,Point-E,Dakar,Cheikh Toure
10,Kymco Agility 2021,[],380000,138373,Hann Maristes,Dakar,Max2roues Diaw
11,Kymco Agility 2019,[],150,138317,Keur Massar,Dakar,Boubacar Seydi
12,Triumph Sprint 2000,[],1600000,138267,Sicap Sacré Coeur,Dakar,Jean philipp Coly
13,Suzuki GSX-F 1994,[],1200000,138268,Sicap Sacré Coeur,Dakar,Jean philipp Coly
14,BMW GS 2015,[],3500000,138206,Keur Massar,Dakar,Babacar Dramé
15,Peugeot Scoot 2019,[],750000,138200,Biscuiterie,Dakar,Abdoul Diop
16,Yamaha X-Max 2006,[],700000,138190,Sicap Liberté,Dakar,Mathieu Sagna
17,Suzuki Burgman 2021,[],1300000,138179,Nord Foire,Dakar,LodiaMiff Deals
18,Kymco Xciting 2021,[],1900000,138154,Liberté 6 extension,Dakar,Al Amine
19,Honda XRV Africa Twin 2018,[],3600000,138100,Plateau,Dakar,HONDA AFRICA TWIN CRF1000

In [8]:
# Divisions de la colonne 'Marque_Modele_Annee' partir des espaces
split_columns = df['Marque_Modele_Annee'].str.split(' ', expand=True)

In [9]:
split_columns

          0        1       2     3     4
0    Yamaha     TMax    2012  None  None
1   Piaggio  Liberty    2020  None  None
2   Peugeot    Tweet    2022  None  None
3     Kymco     Mxer    2020  None  None
4     Kymco   People    2017  None  None
5   Piaggio  Beverly    2011  None  None
6   Piaggio  Carnaby    2009  None  None
7     Kymco  Xciting    2021  None  None
8       KTM      SMR    2013  None  None
9       KTM  jakarta    2023  None  None
10    Kymco  Agility    2021  None  None
11    Kymco  Agility    2019  None  None
12  Triumph   Sprint    2000  None  None
13   Suzuki    GSX-F    1994  None  None
14      BMW       GS    2015  None  None
15  Peugeot    Scoot    2019  None  None
16   Yamaha    X-Max    2006  None  None
17   Suzuki  Burgman    2021  None  None
18    Kymco  Xciting    2021  None  None
19    Honda      XRV  Africa  Twin  2018

In [11]:
# Attribution des colonnes fractionnées aux nouvelles colonnes de noms : 'Marque' , 'Model', 'Annee'  
df['Marque'] = split_columns[0]
df['Model'] = split_columns[1]
df['Annee'] = split_columns[2]

In [13]:
# Nouvellle reorganisation des colonnes
df = df[['Marque', 'Model', 'Annee', 'Kilometrage', 'Prix (F CFA)', 'Ref.', 'Adr_Commune', 'Adr_Region', 'Proprio' ]]

In [14]:
# Verification du DataFrame Final avant export en CSV
df.head()

,Marque,Model,Annee,Kilometrage,Prix (F CFA),Ref.,Adr_Commune,Adr_Region,Proprio
0,Yamaha,TMax,2012,[],2350000,138801,VDN,Dakar,Cheikh Tidiane Ndiaye
1,Piaggio,Liberty,2020,[],320000,138717,Hann Maristes,Dakar,doul ba
2,Peugeot,Tweet,2022,[],350000,138623,Scat Urbam,Dakar,ABDOULAYE SIDIBE
3,Kymco,Mxer,2020,[],400000,138598,Sipres,Dakar,Ahmed Sow
4,Kymco,People,2017,[],450000,138592,Hann Bel-Air,Dakar,Mouhamed Niang

In [15]:
# Export du Dataframe dans un CSV file
df.to_csv('Vente_Motos_Scooters_Dakar_Auto_Datas.csv', index=False)